---
title: "A sample code for proposed t-test statistic"
output: html_notebook
---

# Load Packages

```{r lib}
library(dplyr)
library(reshape)
```

# Load Data

* Load DIA report and transform normalized fragment peak area by log10.
* Select required columns only.

```{r data}
dfx <- read.delim("../../data/PXD015446_report/LiP_Quant_Staurosporine_Dose_Response_HeLa_Report.xls", header = TRUE, nrows = 1000000)

dfy <- read.delim("../../data/PXD015446_report/LiP_Quant_Staurosporine_Dose_Response_HeLa_Report.xls", header = TRUE, skip = 1e7, nrows = 100000)

names(dfy) = names(dfx)
df = rbind(dfx, dfy)
```

```{r filter_data}
sub.df <- df %>% 
  filter(F.ExcludedFromQuantification == 'False' & EG.Qvalue < 0.01) %>%
  mutate(F.Log10NormalizedPeakArea = log10(F.NormalizedPeakArea)) %>%
  select(R.Condition, R.Replicate, PG.ProteinGroups, PG.ProteinNames,
         EG.ModifiedSequence, FG.Charge, F.FrgIon, F.FrgLossType, F.Charge,
         F.Log10NormalizedPeakArea)
```

```{r hist}
hist(sub.df$F.Log10NormalizedPeakArea, 50, xlab = "Normalized Peak Area (log10)", main = "Histogram of Fragment Quantity")
```
```{r filter_data_by_quantity}
sub.df.filtered <- sub.df %>% filter(F.Log10NormalizedPeakArea > 0)

print(dim(sub.df.filtered))
```


# Compute Statistics

## Paired t-test

```{r group_map_f_paired}
## Define a wrapper function for paired t test

source("../../R/paired_t_test.R")

compute_paired_on_group <- function(groupdf) {
  ttestout <- as.data.frame(paired_t_test(groupdf$F.Log10NormalizedPeakArea.x, 
                                          groupdf$F.Log10NormalizedPeakArea.y, 
                                          verbose = FALSE))
}
```

```{r paired_t_test}
conditions <- unique(sub.df.filtered$R.Condition)
n_conditions <- length(conditions)
resu_paired <- list()
for (id1 in 1 : (n_conditions - 1)) {
  for (id2 in (id1 + 1) : n_conditions) {
    df1 <- sub.df.filtered %>% filter(R.Condition == conditions[id1])
    df2 <- sub.df.filtered %>% filter(R.Condition == conditions[id2])
    
    dfmerged <- inner_join(df1, df2, 
                           by = c("R.Replicate", "PG.ProteinGroups",
                                  "PG.ProteinNames", "EG.ModifiedSequence",
                                  "FG.Charge", "F.FrgIon", "F.FrgLossType",
                                  "F.Charge"))
    
    resu <- dfmerged %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence) %>% 
      group_modify(~compute_paired_on_group(.x))
    
    resu_paired <- c(resu_paired, resu)
  }
}

resu_paired <- bind_rows(resu_paired)

head(resu_paired)
```

## Independent sample t-test

```{r group_map_f_independent}
## Define a wrapper function for independent sample t test

source("../../R/independent_t_test.R")

compute_indep_on_group <- function(groupdf) {
  ttestout <- as.data.frame(independent_t_test(
    groupdf$EG.Log10Quantity.x, 
    groupdf$EG.Log10Quantity.y, 
    verbose = FALSE))
}
```

```{r independent_t_test}
conditions <- unique(sub.df.filtered$R.Condition)
n_conditions <- length(conditions)
resu_indep <- list()
for (id1 in 1 : (n_conditions - 1)) {
  for (id2 in (id1 + 1) : n_conditions) {
    ## Aggregate by sum
    df1 <- sub.df.filtered %>% 
      filter(R.Condition == conditions[id1]) %>% 
      group_by(R.Replicate, PG.ProteinGroups, PG.ProteinNames,
               EG.ModifiedSequence) %>%
      summarise(EG.Log10Quantity = log10(sum(10 ** F.Log10NormalizedPeakArea)))
    df2 <- sub.df.filtered %>% 
      filter(R.Condition == conditions[id2]) %>% 
      group_by(R.Replicate, PG.ProteinGroups, PG.ProteinNames,
               EG.ModifiedSequence) %>%
      summarise(EG.Log10Quantity = log10(sum(10 ** F.Log10NormalizedPeakArea)))
    
    dfmerged <- inner_join(df1, df2, 
                           by = c("R.Replicate", "PG.ProteinGroups",
                                  "PG.ProteinNames", "EG.ModifiedSequence"))
    
    resu <- dfmerged %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence) %>% 
      group_modify(~compute_indep_on_group(.x))
    
    resu_indep <- c(resu_indep, resu)
  }
}

resu_indep <- bind_rows(resu_indep)

head(resu_indep)
```



