---
title: "A full analysis using the proposed t-test statistic"
output: html_notebook
---

# Load Packages

```{r lib}
library(dplyr)
library(reshape)

require(boot)
require(corpcor)
source("../../R/paired_t_test.R")
source("../../R/independent_t_test.R")
source("../../R/shrinkage_t_test.R")
source("../../R/cov_diff.shrink.R")
```

# Load Data

* Load DIA report and transform normalized fragment peak area by log10.
* Select required columns only.

```{r data}
df <- read.delim("D:/MS_Data/PXD015446_report/LiP_Quant_Staurosporine_Dose_Response_HeLa_Report.xls", header = TRUE)

df <- df %>% 
  filter(F.ExcludedFromQuantification == 'False' & EG.Qvalue < 0.01) %>%
  mutate(F.Log10NormalizedPeakArea = log10(F.NormalizedPeakArea)) %>%
  select(R.Condition, R.Replicate, PG.ProteinGroups, PG.ProteinNames,
         EG.ModifiedSequence, FG.Charge, F.FrgIon, F.FrgLossType, F.Charge,
         F.Log10NormalizedPeakArea)
```

```{r filter_data_by_quantity}
df.filtered <- df %>% filter(F.Log10NormalizedPeakArea > 0)

print(dim(df.filtered))
```
```{r str_df}
str(df.filtered)
```
```{r boxplot_log10npeakarea}
boxplot(F.Log10NormalizedPeakArea ~ R.Condition, 
        data = df.filtered, 
        xlab = "Condition", 
        ylab = "Normalized Peak Area, log10", 
        main = "")
```


# Compute Statistics

```{r group_map_f_paired}
## Define a wrapper function for paired t test

compute_paired_on_group <- function(groupdf) {
  as.data.frame(paired_t_test(
    groupdf$F.Log10NormalizedPeakArea.x, 
    groupdf$F.Log10NormalizedPeakArea.y, 
    verbose = FALSE))
}
```

```{r group_map_f_independent}
## Define a wrapper function for independent sample t test

compute_indep_on_group <- function(groupdf) {
  as.data.frame(independent_t_test(
    groupdf$EG.Log10Quantity.x, 
    groupdf$EG.Log10Quantity.y, 
    verbose = FALSE))
}
```

```{r group_map_f_proposed}
## Define a wrapper function for shrinkage t test
## It is assumed that groupdf consists of a single modified sequence and two 
## conditions

compute_shrink_on_group <- function(groupdf) {
  df.shrink <- groupdf %>% 
    cast(R.Condition + R.Replicate ~ 
             FG.Charge + F.FrgIon + F.FrgLossType + F.Charge,
         value = "F.Log10NormalizedPeakArea", 
         fun.aggregate = mean)
  
  conditions <- unique(df.shrink$R.Condition)
  con_1 <- conditions[1]
  con_2 <- conditions[2]
  dat_con1 <- as.matrix(df.shrink %>% 
                           filter(R.Condition == con_1) %>% 
                           select(-c(R.Condition, R.Replicate)))
  dat_con2 <- as.matrix(df.shrink %>% 
                           filter(R.Condition == con_2) %>% 
                           select(-c(R.Condition, R.Replicate)))
  
  as.data.frame(shrinkage_t_test(
    dat_con1, dat_con2, verbose = FALSE
  ))
}
```


```{r paired_t_test}
conditions <- unique(df.filtered$R.Condition)
n_conditions <- length(conditions)
resu_paired <- resu_indep <- resu_shrink <- list()
for (id1 in 1 : (n_conditions - 1)) {
  for (id2 in (id1 + 1) : n_conditions) {
    pretreat.df <- df.filtered %>% 
      filter((R.Condition == conditions[id1]) | 
               (R.Condition == conditions[id2])) 
    
    # Paired t test
    df.paired <- pretreat.df %>% 
      cast(PG.ProteinGroups + PG.ProteinNames + EG.ModifiedSequence + 
             R.Replicate + FG.Charge +
             F.FrgIon + F.FrgLossType + F.Charge ~ R.Condition, 
           value = "F.Log10NormalizedPeakArea", 
           fun.aggregate = mean)
    colnames(df.paired)[c(9,10)] <- c("F.Log10NormalizedPeakArea.x", 
                                      "F.Log10NormalizedPeakArea.y")
    resu_paired0 <- df.paired %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence) %>% 
      group_modify(~compute_paired_on_group(.x))
    resu_paired <- c(resu_paired, resu_paired0)
    
    # Independent t test 
    df.indep <- pretreat.df %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence, 
               R.Replicate, R.Condition) %>%
      summarise(EG.Log10Quantity = 
                  log10(sum(10 ** F.Log10NormalizedPeakArea))) %>% 
      cast(PG.ProteinGroups + PG.ProteinNames + EG.ModifiedSequence + 
             R.Replicate ~ R.Condition, 
           value = "EG.Log10Quantity")
    colnames(df.indep)[c(5,6)] <- c("EG.Log10Quantity.x", 
                                    "EG.Log10Quantity.y")
    resu_indep0 <- df.indep %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence) %>%
      group_modify(~compute_indep_on_group(.x))
    resu_indep <- c(resu_indep, resu_indep0)
    
    # Shrinkage t test
    resu_shrink0 <- pretreat.df %>% 
      group_by(PG.ProteinGroups, PG.ProteinNames, EG.ModifiedSequence) %>%
      group_modify(~compute_shrink_on_group(.x))
    resu_shrink <- c(resu_shrink, resu_shrink0)
    
  }
}

resu_paired <- bind_rows(resu_paired)
resu_indep <- bind_rows(resu_indep)
resu_shrink <- bind_rows(resu_shrink)

head(resu_paired)
head(resu_indep)
head(resu_shrink)
```

```{r save}
write.csv(resu_paired, file = "resu_paired.csv", row.names = FALSE)
write.csv(resu_indep, file = "resu_indep.csv", row.names = FALSE)
write.csv(resu_shrink, file = "resu_shrink.csv", row.names = FALSE)
```



