#' Convert spectronaut fragment ion report into standard report
#'
#' @param sn_report A spectronaut fragment ion report. Required columns are
#'   R.Condition, R.Replicate, PG.ProteinGroups, EG.ModifiedSequence,
#'   FG.Charge, EG.Qvalue, F.NormalizedPeakArea,
#'   F.FrgIon, F.FrgLossType, F.Charge, F.ExcludedFromQuantification.
#' @param filter_identified TRUE if only identified precursors remain in the
#'   report.
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, precursor_qvalue, fragment_id, fragment_peak_area
#' @export
convert_sn_to_standard <- function(sn_report, filter_identified = TRUE) {

  # Filter
  if (filter_identified) {
    sn_report <- sn_report[
      (sn_report$F.ExcludedFromQuantification == "False") &
        (sn_report$EG.Qvalue <= 0.01) &
        (sn_report$F.NormalizedPeakArea > 1), ]
  } else {
    sn_report <- sn_report[
      (sn_report$F.ExcludedFromQuantification == "False") &
        (sn_report$F.NormalizedPeakArea > 1), ]
  }

  # Select columns
  sn_report <- sn_report %>%
    dplyr::select(
      R.Condition, R.Replicate, PG.ProteinGroups,
      EG.ModifiedSequence, EG.Qvalue, FG.Charge,
      F.FrgIon, F.FrgLossType, F.Charge, F.NormalizedPeakArea
    )

  # Rename columns
  condition_labels <- unique(sn_report$R.Condition)
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  sn_report <- sn_report %>%
    dplyr::mutate(
      condition = factor(.data$R.Condition, labels = condition_labels),
      experiment = "EXP",
      precursor_id = paste0(.data$EG.ModifiedSequence, ".", .data$FG.Charge),
      fragment_id = paste0(
        .data$F.FrgIon, .data$F.FrgLossType, ".", .data$F.Charge
      )
    ) %>%
    dplyr::rename(
      replicate = .data$R.Replicate,
      protein_id = .data$PG.ProteinGroups,
      precursor_qvalue = .data$EG.Qvalue,
      fragment_peak_area = .data$F.NormalizedPeakArea
    ) %>%
    dplyr::select(
      -c(R.Condition, EG.ModifiedSequence, FG.Charge,
         F.FrgIon, F.FrgLossType, F.Charge)
    )

  return(sn_report)
}


#' Convert MSstats format into standard report
#'
#' MSstats format is generated by running MSstatsConvert::*toMSstatsFormat().
#' No preprocessing is carried out, but column names are changed.
#' @param ms_report A report in MSstats format. Required columns are
#' ProteinName, PeptideSequence, PrecursorCharge, FragmentIon, ProductCharge,
#' Condition, BioReplicate, Run, Intensity
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, fragment_id, fragment_peak_area
#' @export
convert_ms_to_standard <- function(ms_report) {

  ms_report <- ms_report[
    !is.na(ms_report$Intensity) & ms_report$Intensity > 1, ]

  # Rename columns
  condition_labels <- unique(ms_report$Condition)
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  ms_report <- ms_report %>%
    dplyr::mutate(
      condition = factor(.data$Condition, labels = condition_labels),
      precursor_id = paste0(.data$PeptideSequence, ".", .data$PrecursorCharge),
      fragment_id = paste0(.data$FragmentIon, ".", .data$ProductCharge)
    ) %>%
    dplyr::rename(
      replicate = .data$BioReplicate,
      experiment = .data$Run,
      protein_id = .data$ProteinName,
      fragment_peak_area = .data$Intensity
    ) %>%
    dplyr::select(
      -c(Condition, PeptideSequence, PrecursorCharge,
         FragmentIon, ProductCharge)
    )

  # Update replicate
  ms_report <- ms_report %>%
    dplyr::group_by(condition, protein_id, precursor_id, fragment_id) %>%
    dplyr::mutate(replicate = as.numeric(as.factor(.data$replicate)))

  return(ms_report)
}
