#' Convert spectronaut fragment ion report into standard report
#'
#' @param sn_report A spectronaut fragment ion report. Required columns are
#'   R.Condition, R.Replicate, PG.ProteinGroups, EG.ModifiedSequence,
#'   FG.Charge, EG.Qvalue, F.NormalizedPeakArea,
#'   F.FrgIon, F.FrgLossType, F.Charge, F.ExcludedFromQuantification.
#' @param filter_identified TRUE if only identified precursors remain in the
#'   report.
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, precursor_qvalue, fragment_id, fragment_peak_area
#' @export
convert_sn_to_standard <- function(sn_report, filter_identified = TRUE) {

  # Filter
  if (filter_identified) {
    sn_report <- sn_report[
      (sn_report$F.ExcludedFromQuantification == "False") &
        (sn_report$EG.Qvalue <= 0.01) &
        (sn_report$F.NormalizedPeakArea > 1), ]
  } else {
    sn_report <- sn_report[
      (sn_report$F.ExcludedFromQuantification == "False") &
        (sn_report$F.NormalizedPeakArea > 1), ]
  }

  # Select columns
  sn_report <- sn_report %>%
    dplyr::select(
      R.Condition, R.Replicate, PG.ProteinGroups,
      EG.ModifiedSequence, EG.Qvalue, FG.Charge,
      F.FrgIon, F.FrgLossType, F.Charge, F.NormalizedPeakArea
    )

  # Rename columns
  condition_labels <- sort(unique(sn_report$R.Condition))
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  sn_report <- sn_report %>%
    dplyr::mutate(
      condition = factor(.data$R.Condition, labels = condition_labels),
      experiment = "EXP",
      precursor_id = paste0(.data$EG.ModifiedSequence, ".", .data$FG.Charge),
      fragment_id = paste0(
        .data$F.FrgIon, .data$F.FrgLossType, ".", .data$F.Charge
      )
    ) %>%
    dplyr::rename(
      replicate = .data$R.Replicate,
      protein_id = .data$PG.ProteinGroups,
      precursor_qvalue = .data$EG.Qvalue,
      fragment_peak_area = .data$F.NormalizedPeakArea
    ) %>%
    dplyr::select(
      -c(R.Condition, EG.ModifiedSequence, FG.Charge,
         F.FrgIon, F.FrgLossType, F.Charge)
    )

  return(sn_report)
}


#' Convert MSstats format into standard report
#'
#' Convert MSstats format into standard report.
#' MSstats format is generated by running MSstatsConvert::*toMSstatsFormat().
#' Rows are filtered based on fragment peak area, and column names are changed.
#' @param ms_report A report in MSstats format. Required columns are
#'   ProteinName, PeptideSequence, PrecursorCharge, FragmentIon, ProductCharge,
#'   Condition, BioReplicate, Run, Intensity
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, fragment_id, fragment_peak_area
#' @export
convert_ms_to_standard <- function(ms_report) {

  ms_report <- ms_report[
    !is.na(ms_report$Intensity) & ms_report$Intensity > 1, ]

  # Rename columns
  condition_labels <- sort(unique(ms_report$Condition))
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  ms_report <- ms_report %>%
    dplyr::mutate(
      condition = factor(.data$Condition, labels = condition_labels),
      experiment = "EXP",
      precursor_id = paste0(.data$PeptideSequence, ".", .data$PrecursorCharge),
      fragment_id = paste0(.data$FragmentIon, ".", .data$ProductCharge)
    ) %>%
    dplyr::rename(
      replicate = BioReplicate,
      protein_id = ProteinName,
      fragment_peak_area = Intensity
    ) %>%
    dplyr::select(
      -c(Run, Condition, PeptideSequence, PrecursorCharge,
         FragmentIon, ProductCharge)
    )

  # Update replicate
  ms_report <- ms_report %>%
    dplyr::group_by(condition, protein_id, precursor_id, fragment_id) %>%
    dplyr::mutate(replicate = as.numeric(as.factor(.data$replicate))) %>%
    dplyr::ungroup()
}


#' Convert MaxQuant report into standard report
#'
#' Convert MaxQuant report into standard report. MaxQuant report consists of
#' evidence.txt data, msms.txt data, and annotation data.
#' @param evidence MaxQuant evidence.txt data
#' @param msms MqxQuant msms.txt data
#' @param annotation Data frame with columns Raw.file, Condition, BioReplicate,
#'   IsotopeLabelType
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, fragment_id, fragment_peak_area
#' @export
convert_mq_to_standard <- function(evidence, msms, annotation = NULL) {

  # Choose columns
  evidence <- evidence %>% dplyr::select(Modified.sequence, Proteins, Raw.file,
                                  Experiment, Charge, Q.value, Intensity, id)

  # Filter by q-value
  evidence <- evidence %>% dplyr::filter(Q.value <= 0.01)

  # Remove decoy
  evidence <- evidence %>% dplyr::filter(substr(Proteins, 1, 3) != "CON")

  # Expand msms to fragment ion level.
  matches <- strsplit(msms$Matches, ";")
  intensities <- strsplit(msms$Intensities, ";")
  id_top3 <- lapply(
    intensities,
    function(x) {
      sort.list(as.numeric(x), decreasing = TRUE) <= 3
    }
  )
  n_frags <- sapply(matches, length)
  id <- rep(msms$id, n_frags)
  msms <- data.frame(
    Matches = unlist(matches),
    Intensities = unlist(intensities),
    id_top3 = unlist(id_top3),
    id = unlist(id)
  )

  # Select top-3 fragment ions for each precursor
  msms <- msms %>% dplyr::filter(id_top3)

  # Append Matches and Intensities columns
  evidence <- evidence %>% dplyr::left_join(msms, by = "id")

  # Append Raw.file, Condition, BioReplicate, IsotopeLabelType
  evidence <- evidence %>% dplyr::left_join(annotation, by = "Raw.file")

  # Choose unique rows with the smallest Q.value
  evidence <- evidence %>%
    dplyr::arrange(Q.value) %>%
    dplyr::distinct(Proteins, Modified.sequence, Charge, Matches, BioReplicate,
                    Condition, .keep_all = TRUE)

  # Rename columns
  condition_labels <- sort(unique(annotation$Condition))
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  evidence <- evidence %>%
    dplyr::mutate(
      condition = factor(.data$Condition, labels = condition_labels),
      experiment = "EXP",
      precursor_id = paste0(.data$Modified.sequence, ".", .data$Charge),
      fragment_peak_area = as.numeric(Intensities)
    ) %>%
    dplyr::rename(
      replicate = BioReplicate,
      protein_id = Proteins,
      fragment_id = Matches,
      precursor_quantity = Intensity
    ) %>%
    dplyr::select(
      -c(Raw.file, Condition, Modified.sequence, Charge, Experiment, Q.value,
         id, IsotopeLabelType, id_top3, Intensities)
    )

  # Update replicate
  evidence <- evidence %>%
    dplyr::group_by(condition, protein_id, precursor_id, fragment_id) %>%
    dplyr::mutate(replicate = as.numeric(as.factor(.data$replicate))) %>%
    dplyr::ungroup()
}


#' Convert Skyline transition report into standard report
#'
#' Convert Skyline transition report into standard report.
#' Rows are filtered based on fragment peak area, and column names are changed.
#' @param sk_report A report in Skyline transition. Required columns are
#'   Peptide, Protein, Fragment.Ion, Replicate, Area. The Replicate column is
#'   unique to each Run.
#' @param annotation Data frame with columns Condition, Replicate, Run
#' @importFrom dplyr %>%
#' @return A standard report with columns condition, replicate, experiment,
#'   protein_id, precursor_id, fragment_id, fragment_peak_area
#' @export
convert_sk_to_standard <- function(sk_report, annotation) {

  sk_report$Area <- as.numeric(sk_report$Area)
  sk_report <- sk_report %>% dplyr::filter(
    !is.na(Area) & Area > 1 & substr(Protein, 1, 5) != "Decoy"
  )

  # Append Condition, Run
  sk_report <- merge(sk_report, annotation, by = "Replicate", all.x = TRUE)

  # Rename columns
  condition_labels <- sort(unique(sk_report$Condition))
  if ("DMSO" %in% condition_labels) {
    condition_labels <- c("DMSO", condition_labels[condition_labels != "DMSO"])
  }

  sk_report <- sk_report %>%
    dplyr::mutate(
      condition = factor(.data$Condition, labels = condition_labels),
      experiment = "EXP",
      precursor_id = paste0(Peptide, ".", Precursor.Charge),
      fragment_id = paste0(Fragment.Ion, ".", Product.Charge),
    ) %>%
    dplyr::rename(
      replicate = Replicate,
      protein_id = Protein,
      fragment_peak_area = Area
    ) %>%
    dplyr::select(
      -c(
        Run, Condition, Peptide, Precursor.Charge, Fragment.Ion, Product.Charge
      )
    )

  # Update replicate
  sk_report <- sk_report %>%
    dplyr::group_by(condition, protein_id, precursor_id, fragment_id) %>%
    dplyr::mutate(replicate = as.numeric(as.factor(.data$replicate))) %>%
    dplyr::ungroup()
}


#' Convert standard report into MSstatsLiP format
#'
#' No preprocessing is carried out, but column names are changed.
#' @param report A standard report. Required columns are condition, replicate,
#'   experiment, protein_id, precursor_id, fragment_id, fragment_peak_area.
#' @param drop_experiment If TRUE, `experiment` column is removed from output.
#'   Default is FALSE.
#' @importFrom dplyr %>%
#' @return An MSstatsLiP format with columns ProteinName, PeptideSequence,
#'   PrecursorCharge, FragmentIon, ProductCharge, Condition, BioReplicate, Run,
#'   Intensity, FULL_PEPTIDE
#' @export
convert_standard_to_mslip <- function(report, drop_experiment = FALSE) {

  # BioReplicate as a unique number for each condition x replicate
  n_rep_per_cond <- max(as.numeric(report$replicate), na.rm = TRUE)
  report <- report %>% dplyr::mutate(
    BioReplicate = (
      (as.numeric(as.factor(.data$condition)) - 1) * n_rep_per_cond +
      as.numeric(.data$replicate)
    ),
    Run = paste(.data$condition, .data$replicate, sep = "_"),
    Fraction = 1,
    IsotopeLabelType = "L"
  )

  # precursor, fragment ion
  split_precursor_id <- strsplit(report$precursor_id, "[.]")
  report[["PeptideSequence"]] <- sapply(split_precursor_id, function(s) s[1])
  report[["PrecursorCharge"]] <- sapply(
    split_precursor_id, function(s) as.numeric(s[2])
  )

  split_fragment_id <- strsplit(report$fragment_id, "[.]")
  report[["FragmentIon"]] <- sapply(split_fragment_id, function(s) s[1])
  report[["ProductCharge"]] <- sapply(
    split_fragment_id, function(s) as.numeric(s[2])
  )

  # condition, experiment
  report <- report %>%
    dplyr::rename(
      ProteinName = .data$protein_id,
      Condition = .data$condition,
      Intensity = .data$fragment_peak_area
    ) %>%
    dplyr::mutate(
      FULL_PEPTIDE = paste(.data$ProteinName, .data$PeptideSequence, sep = "_")
    )

  if (drop_experiment) {
    report <- report %>%
      dplyr::select(-c(experiment, replicate, precursor_id, fragment_id))
  } else {
    report <- report %>%
      dplyr::select(-c(replicate, precursor_id, fragment_id))
  }

  return(report)
}


#' Create annotation data for MSstats
#'
#' Annotation is required by MSstats for importing reports, such as
#' MaxQuant. Annotation data consists of Condition, Raw.file, BioReplicate,
#' and IsotopeLabelType. Condition column is inferred from Experiment column.
#' @param evidence A data frame including the columns named by `file_column` and
#'   `exp_column`.
#' @param n_replicates_per_condition Number of replicates per condition.
#'   If not NULL, it is assumed that Experiment is n_condition x
#'   n_replicates_per_condition.
#' @param file_column Column name for run files
#' @param exp_column Column name for Experiment
#' @importFrom dplyr %>%
#' @return Annotation data frame.
#' @export
create_annotation_df <- function(
  evidence,
  n_replicates_per_condition = NULL,
  file_column = "Raw.file",
  exp_column = "Experiment"
) {
  # Assume each sample is a biological replicate
  raw_to_exp_match <- evidence[, c(file_column, exp_column)] %>%
    dplyr::distinct_at(file_column, .keep_all = TRUE)

  ## Get raw_files
  raw_files <- raw_to_exp_match[[file_column]]
  n_samples <- length(raw_files)

  if (!is.null(n_replicates_per_condition)) {
    n_conditions <- n_samples / n_replicates_per_condition

    if (n_conditions != floor(n_conditions)) {
      # Reset incorrect parameter to NULL
      n_replicates_per_condition <- NULL
    } else {
      # Infer Conditions
      # from a substring of Experiment;
      # Number of the unique substrings equals to the number of conditions
      len_exp_char <- nchar(raw_to_exp_match[[exp_column]][1])

      for (len_con_char in len_exp_char:1) {
        conditions <- substr(raw_to_exp_match[[exp_column]], 1, len_con_char)
        if (length(unique(conditions) == n_conditions)) {
          break
        }
      }

      if (length(unique(conditions) != n_conditions)) {
        # Reset incorrect parameter
        n_replicates_per_condition <- NULL
      }
    }
  }

  if (is.null(n_replicates_per_condition)) {
    # Infer Conditions
    # Assume the first n letters and 1 number from Experiment denotes Condition
    # For example, "CON1R3" corresponds to "CON1"
    tokens <- strsplit(raw_to_exp_match[[exp_column]][1], "[0-9]")[[1]]
    conditions <- substr(
      raw_to_exp_match[[exp_column]], 1, nchar(tokens[1]) + 1
    )
  }

  annotation_tab <- data.frame(
    Raw.file = raw_files,
    Condition = conditions,
    BioReplicate = seq(from = 1, to = n_samples),
    IsotopeLabelType = rep("L", n_samples)
  )

  return(annotation_tab)
}
